name: siamese
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03=py37_0
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - alabaster=0.7.12=py_0
  - anaconda=custom=py37_1
  - anaconda-client=1.7.2=py_0
  - anaconda-project=0.8.3=py_0
  - apsw=3.30.1.r1=py37he6d99f7_0
  - asn1crypto=1.3.0=py37hc8dfbb8_1
  - astroid=2.4.2=py37hc8dfbb8_0
  - astropy=4.0.1.post1=py37h8f50634_0
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=19.3.0=py_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py_0
  - backports=1.0=py_2
  - backports.os=0.1.1=py37hc8dfbb8_1002
  - backports.shutil_get_terminal_size=1.0.0=py_3
  - beautifulsoup4=4.9.1=py37hc8dfbb8_0
  - bitarray=1.2.2=py37h8f50634_0
  - bkcharts=0.2=py37_0
  - blas=1.0=mkl
  - bleach=3.1.5=pyh9f0ad1d_0
  - blosc=1.19.0=he1b5a44_0
  - bokeh=2.0.1=py37hc8dfbb8_0
  - boost=1.72.0=py37h9de70de_0
  - boost-cpp=1.72.0=h8e57a91_0
  - boto=2.49.0=py_0
  - bottleneck=1.3.2=py37h03ebfcd_1
  - brotli=1.0.7=he1b5a44_1002
  - brotlipy=0.7.0=py37h8f50634_1000
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.0=py37hd463f26_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - charls=2.1.0=he1b5a44_2
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=1.4.1=py_0
  - clyent=1.2.2=py_1
  - colorama=0.4.3=py_0
  - contextlib2=0.6.0.post1=py_0
  - cryptography=2.9.2=py37hb09aad4_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - curl=7.69.1=h33f0ec9_0
  - cycler=0.10.0=py_2
  - cython=0.29.19=py37h3340039_0
  - cytoolz=0.10.1=py37h516909a_0
  - dask=2.18.0=py_0
  - dask-core=2.18.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.18.0=py37hc8dfbb8_0
  - docutils=0.16=py37hc8dfbb8_1
  - entrypoints=0.3=py37hc8dfbb8_1001
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.9=he1b5a44_2
  - fastcache=1.1.0=py37h8f50634_1
  - filelock=3.0.12=pyh9f0ad1d_0
  - flask=1.1.2=pyh9f0ad1d_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=he06d7ca_0
  - fribidi=1.0.9=h516909a_0
  - fsspec=0.7.4=py_0
  - get_terminal_size=1.0.0=haa9412d_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - gevent=20.6.0=py37h8f50634_1
  - giflib=5.2.1=h516909a_2
  - glib=2.64.3=h6f030ca_0
  - glob2=0.7=py_0
  - gmp=6.2.0=he1b5a44_2
  - gmpy2=2.1.0b1=py37h04dde30_0
  - graphite2=1.3.13=he1b5a44_1001
  - greenlet=0.4.16=py37h8f50634_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - h5py=2.10.0=nompi_py37h513d04c_102
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - heapdict=1.0.1=py_0
  - html5lib=1.0.1=py_0
  - hypothesis=5.16.0=py_0
  - icu=64.2=he1b5a44_1
  - idna=2.9=py_1
  - imagecodecs=2020.5.30=py37hda6ee5b_1
  - imageio=2.8.0=py_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.6.1=py37hc8dfbb8_0
  - importlib_metadata=1.6.1=0
  - intel-openmp=2019.4=243
  - ipykernel=5.3.0=py37h43977f1_0
  - ipython=7.15.0=py37hc8dfbb8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37hc8dfbb8_1
  - itsdangerous=1.1.0=py_0
  - jbig=2.1=h516909a_2002
  - jdcal=1.4.1=py_0
  - jedi=0.17.0=py37hc8dfbb8_0
  - jeepney=0.4.3=py_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.15.1=py_0
  - jpeg=9d=h516909a_0
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - jupyterlab=2.1.4=py_0
  - jupyterlab_server=1.1.5=py_0
  - jxrlib=1.1=h516909a_2
  - keyring=21.2.1=py37hc8dfbb8_0
  - kiwisolver=1.2.0=py37h99015e2_0
  - krb5=1.17.1=h2fd8d38_0
  - lazy-object-proxy=1.4.3=py37h8f50634_2
  - lcms2=2.9=hbd6801e_2
  - libaec=1.0.4=he1b5a44_1
  - libarchive=3.3.3=h3a8160c_1008
  - libclang=9.0.1=default_hde54327_0
  - libcurl=7.69.1=hf7181ac_0
  - libedit=3.1.20191231=h46ee950_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.5.0=hdf63c60_6
  - libiconv=1.15=h516909a_1006
  - liblief=0.9.0=hf8a498c_1
  - libllvm8=8.0.1=hc9558a2_0
  - libllvm9=9.0.1=he513fc3_1
  - libpng=1.6.37=hed695b0_1
  - libsodium=1.0.17=h516909a_0
  - libssh2=1.9.0=hab1572f_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc7e4089_6
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - libxslt=1.1.33=h31b3aaa_0
  - libzopfli=1.0.3=he1b5a44_0
  - llvm-openmp=10.0.0=hc9558a2_0
  - llvmlite=0.32.0=py37h5202443_0
  - locket=0.2.0=py_2
  - lxml=4.5.1=py37he3881c9_0
  - lz4-c=1.9.2=he1b5a44_1
  - lzo=2.10=h14c3975_1000
  - markupsafe=1.1.1=py37h8f50634_1
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py37h30547a4_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py37h8f50634_1001
  - mkl=2019.5=281
  - mkl-service=2.3.0=py37h516909a_0
  - mkl_fft=1.1.0=py37hc1659b7_1
  - mkl_random=1.1.0=py37hd6b4f25_0
  - mock=4.0.2=py37hc8dfbb8_0
  - molvs=0.1.1=py_0
  - more-itertools=8.3.0=py_1
  - mpc=1.1.0=h04dde30_1007
  - mpfr=4.0.2=he80fd80_1
  - mpmath=1.1.0=py_0
  - msgpack-python=1.0.0=py37h99015e2_1
  - multipledispatch=0.6.0=py_0
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.6=py_0
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.4=py_1
  - ninja=1.10.0=hc9558a2_0
  - nltk=3.4.4=py_0
  - nose=1.3.7=py37hc8dfbb8_1004
  - notebook=6.0.3=py37hc8dfbb8_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numba=0.49.1=py37h0da4684_0
  - numexpr=2.7.1=py37h0da4684_1
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - numpydoc=1.0.0=pyh9f0ad1d_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h981e76c_3
  - openpyxl=3.0.3=py_0
  - openssl=1.1.1g=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.1=py37h0573a6f_0
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=h7062337_4
  - parso=0.7.0=pyh9f0ad1d_0
  - partd=1.1.0=py_0
  - patchelf=0.10=he1b5a44_0
  - path.py=12.0.1=py_0
  - pathlib2=2.3.5=py37hc8dfbb8_1
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pep8=1.7.1=py_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=7.1.2=py37h718be6c_0
  - pip=20.1.1=py_1
  - pixman=0.38.0=h516909a_1003
  - pkginfo=1.5.0.1=py_0
  - pluggy=0.13.1=py37hc8dfbb8_1
  - ply=3.11=py_1
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - psutil=5.7.0=py37h8f50634_1
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.8.1=py_0
  - py-lief=0.9.0=py37he1b5a44_1
  - pycairo=1.19.1=py37h01af8b0_3
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycosat=0.6.3=py37h8f50634_1004
  - pycparser=2.20=py_0
  - pycrypto=2.6.1=py37h8f50634_1004
  - pycurl=7.43.0.5=py37h16ce93b_0
  - pyflakes=2.2.0=pyh9f0ad1d_0
  - pygments=2.6.1=py_0
  - pylint=2.5.2=py37hc8dfbb8_0
  - pyodbc=4.0.30=py37he1b5a44_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h8685d9f_3
  - pyrsistent=0.16.0=py37h8f50634_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - pytables=3.6.1=py37h9f153d1_1
  - pytest=5.4.3=py37hc8dfbb8_0
  - pytest-arraydiff=0.3=py_0
  - pytest-astropy=0.7.0=py_0
  - pytest-astropy-header=0.1.2=py_0
  - pytest-doctestplus=0.7.0=pyh9f0ad1d_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.1=py_0
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.1=py_0
  - python-libarchive-c=2.9=py37_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2020.1=pyh9f0ad1d_0
  - pywavelets=1.1.1=py37h03ebfcd_1
  - pyyaml=5.3.1=py37h8f50634_0
  - pyzmq=19.0.1=py37hac76be4_0
  - qt=5.12.5=hd8c4c69_1
  - qtawesome=0.7.2=pyh9f0ad1d_0
  - qtconsole=4.7.4=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - rdkit=2020.03.2=py37hdd87690_0
  - readline=7.0=hf8c457e_1001
  - requests=2.23.0=pyh8c360ce_2
  - rope=0.17.0=pyh9f0ad1d_0
  - ruamel_yaml=0.15.80=py37h8f50634_1001
  - scikit-image=0.17.2=py37h0da4684_0
  - scikit-learn=0.22.1=py37hd81dba3_0
  - scipy=1.4.1=py37h0b6359f_0
  - seaborn=0.10.1=py_0
  - secretstorage=3.1.2=py37hc8dfbb8_1
  - send2trash=1.5.0=py_0
  - setuptools=47.1.1=py37hc8dfbb8_0
  - simplegeneric=0.8.1=py_1
  - singledispatch=3.4.0.3=py37_1000
  - sip=4.19.22=py37h3340039_0
  - six=1.15.0=pyh9f0ad1d_0
  - snappy=1.1.8=he1b5a44_1
  - snowballstemmer=2.0.0=py_0
  - sortedcollections=1.2.1=pyh9f0ad1d_0
  - sortedcontainers=2.2.1=pyh9f0ad1d_0
  - soupsieve=2.0.1=py37hc8dfbb8_0
  - sphinx=3.1.0=py_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sphinxcontrib-websupport=1.2.2=pyh9f0ad1d_0
  - spyder=3.3.6=py37_0
  - spyder-kernels=0.5.1=py37_0
  - sqlalchemy=1.3.17=py37h8f50634_0
  - sqlite=3.31.1=h7b6447c_0
  - statsmodels=0.11.1=py37h8f50634_1
  - sympy=1.6=py37hc8dfbb8_0
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tifffile=2020.6.3=py_1
  - tk=8.6.10=hed695b0_0
  - toml=0.10.1=pyh9f0ad1d_0
  - toolz=0.10.0=py_0
  - torchvision=0.4.2=py37_cu101
  - tornado=6.0.4=py37h8f50634_1
  - tqdm=4.46.1=pyh9f0ad1d_0
  - traitlets=4.3.3=py37hc8dfbb8_1
  - typed-ast=1.4.1=py37h516909a_0
  - typing_extensions=3.7.4.2=py_0
  - unicodecsv=0.14.1=py_1
  - unixodbc=2.3.7=hd1b7508_1000
  - urllib3=1.25.9=py_0
  - wcwidth=0.2.4=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h8f50634_0
  - wurlitzer=2.0.0=py37hc8dfbb8_1
  - xlrd=1.2.0=py_0
  - xlsxwriter=1.2.9=pyh9f0ad1d_0
  - xlwt=1.3.0=py_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_0
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.2=he1b5a44_2
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zope.event=4.4=pyh9f0ad1d_0
  - zope.interface=5.1.0=py37h8f50634_0
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - cairocffi==1.1.0
    - cairosvg==2.4.2
    - cssselect2==0.3.0
    - drawsvg==1.5.3
    - mmpdb==2.3.dev1
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - skorch==0.6.0
    - svgutils==0.3.1
    - tabulate==0.8.5
    - tinycss2==1.0.2
prefix: /home/kdqm927/miniconda3/envs/siamese
